// frontend/src/app/my-jewels/my-jewels.component.ts
import { Component, OnInit } from '@angular/core';
import { MyJewelsService } from '../api/services/my-jewels.service';
import { Device } from '../api/models/device';
import { Type } from '../api/models';
import { LucidePlus } from 'lucide-angular';
import { AddJewelComponent } from '../add-jewel/add-jewel.component';
import { FormControl, FormGroup } from '@angular/forms';
import { EditJewelComponent } from '../edit-jewel/edit-jewel.component';

enum DetailsTab {
  Software,
  Hardware,
  Device,
  Storage,
  Notes
}

@Component({
  selector: 'app-my-jewels',
  templateUrl: './my-jewels.component.html',
  styleUrl: './my-jewels.component.scss'
})
export class MyJewelsComponent implements OnInit {
  protected readonly LucidePlus = LucidePlus;
  protected readonly Type = Type;
  protected readonly DetailsTab = DetailsTab;

  protected myJewels: Device[] | null = null;

  protected currentDeviceId: string | null = null;

  protected loading = true;
  protected hasError = false;
  protected addHasError = false;
  protected editHasError = false;
  protected deleteHasError = false;
  protected deleteOpen = false;

  protected detailsTab = DetailsTab.Device;

  protected searchTerm = '';

  protected deviceTypeFilter = new Set([Type.Phone, Type.Computer, Type.Other, Type.Watch]);

  protected notesEditor = new FormGroup({
    notes: new FormControl('')
  });

  constructor(private readonly myJewelsService: MyJewelsService) {}

  get devices() {
    return (
      this.myJewels
        ?.filter(
          (d) =>
            d.model.toLocaleLowerCase().includes(this.searchTerm.toLocaleLowerCase()) ||
            d.hostname?.toLocaleLowerCase().includes(this.searchTerm.toLocaleLowerCase()) ||
            d.manufacturer.toLocaleLowerCase().includes(this.searchTerm.toLocaleLowerCase())
        )
        .filter((d) => this.deviceTypeFilter.has(d.type)) ?? []
    );
  }

  get selectedDevice(): Device | null {
    if (!this.devices.find((d) => d.id === this.currentDeviceId)) {
      if (this.devices.length > 0) {
        this.selectDevice(this.devices[0]);
      } else {
        this.currentDeviceId = null;
      }
    }

    return this.devices.find((device) => device.id === this.currentDeviceId) ?? null;
  }

  get selectedDrives() {
    return this.selectedDevice?.drives?.filter((d) => d.size > 0) ?? [];
  }

  get availableTypes() {
    return [...new Set(this.myJewels?.map((jewel) => jewel.type) ?? [])];
  }

  ngOnInit(): void {
    this.loading = true;
    this.loadJewels();
  }

  private loadJewels() {
    this.myJewelsService.getMyJewels().subscribe({
      next: (data) => {
        this.myJewels = data.map((jewel) => ({
          ...jewel,
          eol: jewel.eol ? new Date(Date.parse(jewel.eol as unknown as string)) : undefined
        }));
      },
      error: (error) => {
        this.hasError = true;
        console.error(error);
      },
      complete: () => {
        this.loading = false;
      }
    });
  }

  protected toggleFilter(type: Type) {
    if (this.deviceTypeFilter.has(type)) {
      this.deviceTypeFilter.delete(type);
    } else {
      this.deviceTypeFilter.add(type);
    }
  }

  protected deleteDevice() {
    this.deleteHasError = false;
    this.myJewelsService.deleteMyJewel({ id: this.currentDeviceId! }).subscribe({
      next: () => {
        this.myJewels = this.myJewels?.filter((d) => d.id !== this.currentDeviceId) ?? [];
        this.currentDeviceId = null;
        this.deleteOpen = false;
      },
      error: () => {
        this.deleteHasError = true;
      }
    });
  }

  protected saveManuelJewel(addJewel: AddJewelComponent, device: Device) {
    this.myJewelsService.createMyJewel({ body: { mode: 'manual', jewel: device } }).subscribe({
      next: (jewel) => {
        this.currentDeviceId = jewel.id;
        this.myJewels?.push(jewel);
        addJewel.close();
      },
      error: () => {
        this.addHasError = true;
      }
    });
  }

  protected saveCodeJewel(addJewel: AddJewelComponent, token: string) {
    this.myJewelsService.createMyJewel({ body: { mode: 'auto', token } }).subscribe({
      next: () => {
        this.loadJewels();
        addJewel.close();
      },
      error: () => {
        this.addHasError = true;
      }
    });
  }

  protected selectDevice(device: Device) {
    this.currentDeviceId = device.id;
    this.detailsTab = DetailsTab.Device;
    this.notesEditor.reset({ notes: this.selectedDevice?.notes ?? '' });
  }

  protected saveNotes() {
    this.myJewelsService
      .updateMyJewel({
        id: this.currentDeviceId!,
        body: { ...this.selectedDevice!, notes: this.notesEditor.controls.notes.value ?? '' }
      })
      .subscribe({});
  }

  protected updateJewel(editJewel: EditJewelComponent, device: Device) {
    this.myJewelsService
      .updateMyJewel({
        id: device.id,
        body: { ...device }
      })
      .subscribe({
        next: () => {
          editJewel.close();
          this.editHasError = false;
        },
        error: () => {
          this.editHasError = true;
        }
      });
  }
}

@if (hasError) {
  <div class="cosmo-message is--negative">
    <span class="cosmo-message__header">Fehler beim Laden</span>
    <p class="cosmo-message__message">
      Leider konnten deine Geräte nicht geladen werden, bitte wende dich an deinen Administrator.
    </p>
  </div>
} @else if (loading) {
  <app-loading-spinner />
} @else if (myJewels?.length ?? 0 > 0) {
  <div class="device-list">
    <div class="device-list-items">
      <div class="device-filter-bar">
        @for (type of availableTypes; track type) {
          <button
            type="button"
            class="device-filter-type"
            [class.active]="deviceTypeFilter.has(type)"
            (click)="toggleFilter(type)"
          >
            <div class="device-filter-bubble"></div>
            @switch (type) {
              @case (Type.Watch) {
                Smartwatches
              }
              @case (Type.Phone) {
                Smartphones
              }
              @case (Type.Computer) {
                Computer
              }
              @case (Type.Other) {
                Sonstiges
              }
            }
          </button>
        }
      </div>
      <input
        type="search"
        class="cosmo-input device-search-bar"
        placeholder="Einfach tippen zum Filtern…"
        [(ngModel)]="searchTerm"
      />
      <div class="device-list-items-inner">
        @for (device of devices; track device) {
          <a
            class="device-list-item"
            [class.is--active]="selectedDevice?.id === device.id"
            (click)="selectDevice(device)"
          >
            <span class="device-title">{{ device.manufacturer }} {{ device.model }}</span>
            @if (device.type !== Type.Other) {
              <span class="device-subtitle">{{ device.hostname ?? '' }}</span>
            }
          </a>
        } @empty {
          <div class="cosmo-message is--information">
            <div class="cosmo-message__header">Es wurden keine Geräte gefunden</div>
            <div class="cosmo-message__message">
              Zu deiner Suche haben wir keine Geräte gefunden, möchtest du eins hinzufügen?
            </div>
            <div class="cosmo-button__container">
              <button class="cosmo-button is--primary" (click)="addJewel.open()">Neues Gerät erstellen</button>
            </div>
          </div>
        }
      </div>
      <button class="cosmo-button is--circle is--primary add-button is--large" (click)="addJewel.open()">
        <lucide-icon [img]="LucidePlus" />
      </button>
    </div>
    <div class="device-list-separator"></div>
    <div class="device-list-details">
      @if (selectedDevice) {
        <div class="cosmo-title">
          @if (selectedDevice.type === Type.Computer) {
            {{ selectedDevice.hostname }}
          } @else {
            {{ selectedDevice.manufacturer }} {{ selectedDevice.model }}
          }
          @if (selectedDevice.os) {
            <small>{{ selectedDevice.os.name }} {{ selectedDevice.os.version }}</small>
          }
        </div>
        <div class="cosmo-toolbar">
          <div class="cosmo-toolbar__group">
            <button class="cosmo-button" (click)="editJewel.open()">Bearbeiten</button>
            <button class="cosmo-button is--negative" (click)="deleteOpen = true">Löschen</button>
          </div>
        </div>
        <div class="device-list-details-inner">
          <div class="cosmo-tab">
            <div class="cosmo-tab__links">
              <a
                class="cosmo-tab__link"
                [class.is--active]="detailsTab === DetailsTab.Device"
                (click)="detailsTab = DetailsTab.Device"
              >
                Gerät
              </a>
              @if (selectedDevice.os?.name || selectedDevice.kernel?.version) {
                <a
                  class="cosmo-tab__link"
                  [class.is--active]="detailsTab === DetailsTab.Software"
                  (click)="detailsTab = DetailsTab.Software"
                >
                  Software
                </a>
              }
              @if (selectedDevice.cpu?.cores || selectedDevice.ram || selectedDevice.mainboard || selectedDevice.bios) {
                <a
                  class="cosmo-tab__link"
                  [class.is--active]="detailsTab === DetailsTab.Hardware"
                  (click)="detailsTab = DetailsTab.Hardware"
                >
                  Hardware
                </a>
              }
              @if (selectedDevice.drives?.length ?? 0 > 0) {
                <a
                  class="cosmo-tab__link"
                  [class.is--active]="detailsTab === DetailsTab.Storage"
                  (click)="detailsTab = DetailsTab.Storage"
                >
                  Speichergeräte
                </a>
              }
              <a
                class="cosmo-tab__link"
                [class.is--active]="detailsTab === DetailsTab.Notes"
                (click)="detailsTab = DetailsTab.Notes"
              >
                Notizen
              </a>
            </div>
          </div>
          @if (detailsTab === DetailsTab.Device) {
            <div class="cosmo-tab__content">
              <dl class="cosmo-list is--key-value">
                @if (selectedDevice.hostname) {
                  <dt>Name</dt>
                  <dd>{{ selectedDevice.hostname }}</dd>
                }
                <dt>Hersteller</dt>
                <dd>{{ selectedDevice.manufacturer }}</dd>
                <dt>Model</dt>
                <dd>{{ selectedDevice.model }}</dd>
                @if (selectedDevice.eol) {
                  <dt>Supportende</dt>
                  <dd>{{ selectedDevice.eol.toLocaleDateString() }}</dd>
                }
              </dl>
            </div>
          }
          @if ((selectedDevice.os?.name || selectedDevice.kernel?.version) && detailsTab === DetailsTab.Software) {
            <div class="cosmo-tab__content">
              @if (selectedDevice.os) {
                <h3>Betriebssystem</h3>
                <dl class="cosmo-list is--key-value">
                  <dt>Name</dt>
                  <dd>{{ selectedDevice.os.name }}</dd>
                  <dt>Version</dt>
                  <dd>{{ selectedDevice.os.version }}</dd>
                </dl>
              }
              @if (selectedDevice.kernel) {
                <h3>Kernel</h3>
                <dl class="cosmo-list is--key-value">
                  <dt>Version</dt>
                  <dd>{{ selectedDevice.kernel.version }}</dd>
                  <dt>Architektur</dt>
                  <dd>{{ selectedDevice.kernel.architecture }}</dd>
                </dl>
              }
            </div>
          }
          @if (
            (selectedDevice.cpu?.cores || selectedDevice.ram || selectedDevice.mainboard || selectedDevice.bios) &&
            detailsTab === DetailsTab.Hardware
          ) {
            <div class="cosmo-tab__content">
              @if (selectedDevice.cpu) {
                <h3>Prozessor</h3>
                <dl class="cosmo-list is--key-value">
                  <dt>Hersteller</dt>
                  <dd>{{ selectedDevice.cpu.manufacturer }}</dd>
                  <dt>Model</dt>
                  <dd>{{ selectedDevice.cpu.model }}</dd>
                  @if (selectedDevice.cpu.cores > 0) {
                    <dt>Kerne</dt>
                    <dd>{{ selectedDevice.cpu.cores }}</dd>
                  }
                  @if (selectedDevice.cpu.threads > 0) {
                    <dt>Threads</dt>
                    <dd>{{ selectedDevice.cpu.threads }}</dd>
                  }
                  @if (selectedDevice.cpu.speed > 0) {
                    <dt>Geschwindigkeit</dt>
                    <dd>{{ selectedDevice.cpu.speed.toFixed(2) }} GHz</dd>
                  }
                </dl>
              }
              @if (selectedDevice.storage || selectedDevice.ram) {
                <h3>Speicher</h3>
                <dl class="cosmo-list is--key-value">
                  @if (selectedDevice.storage) {
                    <dt>Speicherplatz</dt>
                    <dd>{{ selectedDevice.storage.toFixed(2) }} GB</dd>
                  }
                  @if (selectedDevice.ram) {
                    <dt>Arbeitsspeicher</dt>
                    <dd>{{ selectedDevice.ram.toFixed(2) }} GB</dd>
                  }
                </dl>
              }
              @if (selectedDevice.mainboard) {
                <h3>Mainboard</h3>
                <dl class="cosmo-list is--key-value">
                  <dt>Hersteller</dt>
                  <dd>{{ selectedDevice.mainboard.manufacturer }}</dd>
                  <dt>Model</dt>
                  <dd>{{ selectedDevice.mainboard.model }}</dd>
                  <dt>Version</dt>
                  <dd>{{ selectedDevice.mainboard.version }}</dd>
                </dl>
              }
              @if (selectedDevice.bios) {
                <h3>BIOS/UEFI</h3>
                <dl class="cosmo-list is--key-value">
                  <dt>Hersteller</dt>
                  <dd>{{ selectedDevice.bios.manufacturer }}</dd>
                  <dt>Version</dt>
                  <dd>{{ selectedDevice.bios.version }}</dd>
                </dl>
              }
            </div>
          }
          @if ((selectedDevice.drives?.length ?? 0 > 0) && detailsTab == DetailsTab.Storage) {
            <div class="cosmo-tab__content">
              @for (drive of selectedDrives; track drive) {
                <h4>{{ drive.name }}</h4>
                <dl class="cosmo-list is--key-value">
                  <dt>Hersteller</dt>
                  <dd>{{ drive.manufacturer }}</dd>
                  <dt>Model</dt>
                  <dd>{{ drive.model }}</dd>
                  <dt>Größe</dt>
                  <dd>{{ drive.size.toFixed(2) }} GB</dd>
                </dl>
              }
            </div>
          }
          @if (detailsTab === DetailsTab.Notes) {
            <form class="cosmo-tab__content" [formGroup]="notesEditor" (ngSubmit)="saveNotes()">
              <quill-editor
                format="html"
                formControlName="notes"
                placeholder="Trag hier deine Notizen zu dem Gerät ein…"
              ></quill-editor>
              <div class="cosmo-button__container">
                <button type="reset" class="cosmo-button">Änderungen verwerfen</button>
                <button type="submit" class="cosmo-button is--primary">Notizen speichern</button>
              </div>
            </form>
          }
        </div>
      }
    </div>
  </div>
  <app-confirm
    [open]="deleteOpen"
    negative
    title="Gerät löschen"
    (confirm)="deleteDevice()"
    (decline)="deleteOpen = false"
    confirmLabel="Gerät löschen"
    declineLabel="Gerät behalten"
  >
    @if (deleteHasError) {
      <div class="cosmo-message is--negative">
        <span class="cosmo-message__header">Fehler beim Löschen</span>
        <p class="cosmo-message__message">
          Leider konnte das Gerät
          @if (selectedDevice?.type === Type.Other) {
            {{ selectedDevice?.manufacturer }} {{ selectedDevice?.model }}
          } @else {
            {{ selectedDevice?.hostname }}
          }
          nicht gelöscht werden, bitte wende dich an deinen Administrator.
        </p>
      </div>
    }
    Soll das Gerät
    @if (selectedDevice?.type === Type.Other) {
      {{ selectedDevice?.manufacturer }} {{ selectedDevice?.model }}
    } @else {
      {{ selectedDevice?.hostname }}
    }
    wirklich gelöscht werden?
  </app-confirm>
} @else {
  <div class="cosmo-message is--information">
    <span class="cosmo-message__header">Keine Geräte</span>
    <p class="cosmo-message__message">Du hast noch keine Geräte erstellt.</p>
    <div class="cosmo-button__container">
      <button class="cosmo-button is--primary" (click)="addJewel.open()">Neues Gerät erstellen</button>
    </div>
  </div>
}

<app-add-jewel
  #addJewel
  (onSubmitCode)="saveCodeJewel(addJewel, $event)"
  (onSubmitManual)="saveManuelJewel(addJewel, $event)"
  [hasError]="addHasError"
/>

<app-edit-jewel
  #editJewel
  (onSubmit)="updateJewel(editJewel, $event)"
  [hasError]="editHasError"
  [device]="selectedDevice!"
/>

// src/routes/my-jewels/+page.svelte
<script lang="ts">
	import { type Device, Type } from '$lib/database/models';
	import { enhance } from '$app/forms';
	import { qr } from '@svelte-put/qr/img';

	export let data;
	export let form;

	let deleteOpen = false;
	let newOpen = false;
	let editOpen = false;
	let newTab = 'code';
	let newDeviceType = Type.PhoneOrTablet;
	let newToken = crypto.randomUUID();

	let selectedDevice: Device | null;
	let searchTerm = '';

	let deviceTypeFilter = new Set([Type.PhoneOrTablet, Type.Computer, Type.Other, Type.Smartwatch]);
	let availableDeviceTypes: Set<Type> = new Set();
	let devices = data?.devices;

	$: selectedDeviceType = selectedDevice?.type as Type;

	$: if (data?.devices) {
		if (data.devices.length > 0) {
			selectedDevice = data.devices[0];
		} else {
			selectedDevice = null;
		}
	}

	function openNew() {
		newDeviceType = Type.PhoneOrTablet;
		newOpen = true;
		newToken = crypto.randomUUID();
	}

	$: if (form?.deleteSuccess) {
		deleteOpen = false;
	}

	$: if (form?.newSuccess) {
		newOpen = false;
	}

	$: if (form?.editSuccess) {
		editOpen = false;
	}

	$: if (data?.devices) {
		availableDeviceTypes = new Set(data?.devices.map((d) => d.type));
	}

	$: {
		devices = data?.devices
			.filter(
				(d) =>
					d.model.toLocaleLowerCase().includes(searchTerm.toLocaleLowerCase()) ||
					d.hostname?.toLocaleLowerCase().includes(searchTerm.toLocaleLowerCase()) ||
					d.manufacturer.toLocaleLowerCase().includes(searchTerm.toLocaleLowerCase())
			)
			.filter((d) => deviceTypeFilter.has(d.type));
		if (!devices.find((d) => d.id === selectedDevice?.id)) {
			if (devices.length > 0) {
				selectedDevice = devices[0];
			} else {
				selectedDevice = null;
			}
		}
	}

	function toggleFilter(type: Type) {
		if (deviceTypeFilter.has(type)) {
			deviceTypeFilter.delete(type);
		} else {
			deviceTypeFilter.add(type);
		}

		deviceTypeFilter = deviceTypeFilter;
	}
</script>

{#if data?.devices.length}
	<div class="device-list">
		<div class="device-list-items">
			<div class="device-filter-bar">
				{#each availableDeviceTypes as type}
					<div
						class="device-filter-type"
						class:active={deviceTypeFilter.has(type)}
						on:click={() => toggleFilter(type)}
					>
						<div class="device-filter-bubble"></div>
						{#if type === Type.PhoneOrTablet}
							Smartphones
						{:else if type === Type.Smartwatch}
							Smartwatches
						{:else if type === Type.Computer}
							Computer
						{:else if type === Type.Other}
							Sonstiges
						{/if}
					</div>
				{/each}
			</div>
			<input
				type="search"
				class="cosmo-input device-search-bar"
				placeholder="Einfach tippen zum Filtern…"
				bind:value={searchTerm}
			/>
			<div class="device-list-items-inner">
				{#each devices as device}
					<div
						class="device-list-item"
						class:is--active={selectedDevice?.id === device.id}
						on:click={() => (selectedDevice = device)}
					>
						<span class="device-title">{device.manufacturer} {device.model}</span>
						{#if device.type !== Type.Other}
							<span class="device-subtitle">{device.hostname ?? ''}</span>
						{/if}
					</div>
				{:else}
					<div class="cosmo-message is--information">
						<div class="cosmo-message__header">Es wurden keine Geräte gefunden</div>
						<div class="cosmo-message__message">
							Zu deiner Suche haben wir keine Geräte gefunden, möchtest du eins hinzufügen?
						</div>
						<div class="cosmo-button__container">
							<button class="cosmo-button is--primary" on:click={openNew}
							>Neues Gerät erstellen
							</button>
						</div>
					</div>
				{/each}
			</div>
			<button class="cosmo-button is--circle is--primary add-button is--large" on:click={openNew}>
				<svg
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="2"
					stroke-linecap="round"
					stroke-linejoin="round"
				>
					<path d="M5 12h14" />
					<path d="M12 5v14" />
				</svg>
			</button>
		</div>
		<div class="device-list-separator"></div>
		<div class="device-list-details">
			{#if selectedDevice}
				<div class="cosmo-title">
					{#if selectedDevice.type === Type.Computer}
						{selectedDevice.hostname}
					{:else}
						{selectedDevice.manufacturer} {selectedDevice.model}
					{/if}
					{#if selectedDevice.os}
						<small>{selectedDevice.os.name ?? ''} {selectedDevice.os.version ?? ''}</small>
					{/if}
				</div>
				<div class="cosmo-toolbar">
					<div class="cosmo-toolbar__group">
						<button class="cosmo-button" on:click={() => (editOpen = true)}>Bearbeiten</button>
						<button class="cosmo-button is--negative" on:click={() => (deleteOpen = true)}
						>Löschen
						</button>
					</div>
				</div>
				<div class="device-list-details-inner">
					<h2>Gerät</h2>
					<dl class="cosmo-list is--key-value">
						{#if selectedDevice.hostname}
							<dt>Name</dt>
							<dd>{selectedDevice.hostname}</dd>
						{/if}
						<dt>Hersteller</dt>
						<dd>{selectedDevice.manufacturer}</dd>
						<dt>Model</dt>
						<dd>{selectedDevice.model}</dd>
						{#if selectedDevice.eol}
							<dt>Supportende</dt>
							<dd>{selectedDevice.eol?.toLocaleDateString()}</dd>
						{/if}
					</dl>
					{#if selectedDevice.os?.name || selectedDevice.kernel?.version}
						<h2>Software</h2>
						{#if selectedDevice.os}
							<h3>Betriebssystem</h3>
							<dl class="cosmo-list is--key-value">
								<dt>Name</dt>
								<dd>{selectedDevice.os.name}</dd>
								<dt>Version</dt>
								<dd>{selectedDevice.os.version ?? ''}</dd>
							</dl>
						{/if}
						{#if selectedDevice.kernel}
							<h3>Kernel</h3>
							<dl class="cosmo-list is--key-value">
								<dt>Version</dt>
								<dd>{selectedDevice.kernel.version}</dd>
								<dt>Architektur</dt>
								<dd>{selectedDevice.kernel.architecture}</dd>
							</dl>
						{/if}
					{/if}
					{#if selectedDevice.cpu?.cores || selectedDevice.storage || selectedDevice.ram || selectedDevice.mainboard || selectedDevice.bios}
						<h2>Hardware</h2>
						{#if selectedDevice.cpu}
							<h3>Prozessor</h3>
							<dl class="cosmo-list is--key-value">
								<dt>Hersteller</dt>
								<dd>{selectedDevice.cpu.manufacturer}</dd>
								<dt>Model</dt>
								<dd>{selectedDevice.cpu.model}</dd>
								<dt>Kerne</dt>
								<dd>{selectedDevice.cpu.cores}</dd>
								<dt>Threads</dt>
								<dd>{selectedDevice.cpu.threads}</dd>
								<dt>Geschwindigkeit</dt>
								<dd>{selectedDevice.cpu.speed.toFixed(2)} GHz</dd>
							</dl>
						{/if}
						{#if selectedDevice.storage || selectedDevice.ram}
							<h3>Speicher</h3>
							<dl class="cosmo-list is--key-value">
								{#if selectedDevice.storage}
									<dt>Speicherplatz</dt>
									<dd>{selectedDevice.storage.toFixed(2)} GB</dd>
								{/if}
								{#if selectedDevice.ram}
									<dt>Arbeitsspeicher</dt>
									<dd>{selectedDevice.ram.toFixed(2)} GB</dd>
								{/if}
							</dl>
						{/if}
						{#if selectedDevice.drives}
							<h3>Festplatten</h3>
							{#each selectedDevice.drives.filter((d) => d.size > 0) as drive}
								<h4>{drive.name}</h4>
								<dl class="cosmo-list is--key-value">
									<dt>Hersteller</dt>
									<dd>{drive.manufacturer}</dd>
									<dt>Model</dt>
									<dd>{drive.model}</dd>
									<dt>Größe</dt>
									<dd>{drive.size.toFixed(2)} GB</dd>
								</dl>
							{/each}
						{/if}
						{#if selectedDevice.mainboard}
							<h3>Mainboard</h3>
							<dl class="cosmo-list is--key-value">
								<dt>Hersteller</dt>
								<dd>{selectedDevice.mainboard.manufacturer}</dd>
								<dt>Model</dt>
								<dd>{selectedDevice.mainboard.model}</dd>
								<dt>Version</dt>
								<dd>{selectedDevice.mainboard.version}</dd>
							</dl>
						{/if}
						{#if selectedDevice.bios}
							<h3>BIOS/UEFI</h3>
							<dl class="cosmo-list is--key-value">
								<dt>Hersteller</dt>
								<dd>{selectedDevice.bios.manufacturer}</dd>
								<dt>Version</dt>
								<dd>{selectedDevice.bios.version}</dd>
							</dl>
						{/if}
					{/if}
				</div>
			{/if}
		</div>
	</div>
{:else}
	<div class="cosmo-message is--information">
		<span class="cosmo-message__header">Keine Geräte</span>
		<p class="cosmo-message__message">Du hast noch keine Geräte erstellt.</p>
		<div class="cosmo-button__container">
			<button class="cosmo-button is--primary" on:click={openNew}>Neues Gerät erstellen</button>
		</div>
	</div>
{/if}
{#if deleteOpen}
	<div class="cosmo-modal__container">
		<form class="cosmo-modal is--negative" method="post" action="?/deleteDevice" use:enhance>
			<input type="hidden" value={selectedDevice?.id} name="selectedDevice" />
			<h1 class="cosmo-modal__title">Gerät löschen</h1>
			<div class="cosmo-modal__content">
				<p>
					Soll das Gerät {selectedDevice?.model} wirklich gelöscht werden?
				</p>
			</div>
			<div class="cosmo-modal__button-bar">
				<button class="cosmo-button" on:click={() => (deleteOpen = false)}>Nicht löschen</button>
				<button class="cosmo-button" type="submit">Löschen</button>
			</div>
		</form>
	</div>
{/if}
{#if newOpen}
	<div class="cosmo-modal__container">
		<form class="cosmo-modal" method="post" action="?/createDevice" use:enhance>
			<h1 class="cosmo-modal__title">Gerät erstellen</h1>
			<div class="cosmo-modal__content">
				<div class="cosmo-tab">
					<div class="cosmo-tab__links">
						<a
							class="cosmo-tab__link"
							class:is--active={newTab === 'code'}
							on:click={() => (newTab = 'code')}>Automatisch</a
						>
						<a
							class="cosmo-tab__link"
							class:is--active={newTab === 'manual'}
							on:click={() => (newTab = 'manual')}>Von Hand</a
						>
					</div>
					<div class="cosmo-tab__content">
						<input type="hidden" value={newTab} name="registryType" />
						{#if newTab === 'code'}
							<div class="jewels-new">
								<div>
									<div class="token">
										<img
											use:qr={{
										data: JSON.stringify({
											token: newToken,
											host: location.origin
										}),
										logo: `${location.origin}/favicon.svg`,
										shape: 'circle',
										anchorInnerFill: '#28aef0',
										anchorOuterFill: '#28aef0',
										moduleFill: '#28aef0',
										backgroundFill: 'transparent',
										width: 450,
										height: 450
									}}
											alt={newToken}
										/>
									</div>
								</div>
								<div>
									<div class="cosmo-message is--information">
										<h3 class="cosmo-message__header">Wozu ist das Token da?</h3>
										<p class="cosmo-message__message">
											Das Token ist für die Jewels App oder den Jewels Linux Client,<br />
											um automatisiert Informationen über dein Gerät in Jewels zu speichern.<br />
											Um die Verwendung möglichst einfach zu machen,<br />
											kannst du den unten angezeigten QR Code einfach mit der Jewels App scannen.<br />
											Wenn du den Linux Client benutzt, musst du die Infos unter dem QR Code eintragen.
										</p>
									</div>
									<div class="cosmo-message is--warning">
										<h3 class="cosmo-message__header">Speicher dir das Token</h3>
										<p class="cosmo-message__message">
											Das Token ist nach dem Speichern nicht mehr verfügbar, bitte speicher es dir ab.
										</p>
									</div>
									<div class="cosmo-input__group">
										<label class="cosmo-label" for="createTokenUrl">Url</label>
										<input
											class="cosmo-input"
											type="text"
											readonly
											id="createTokenUrl"
											value={location.origin}
										/>
										<label class="cosmo-label" for="createTokenToken">Token</label>
										<input
											class="cosmo-input"
											type="text"
											readonly
											id="createTokenToken"
											name="token"
											value={newToken}
										/>
									</div>
								</div>
							</div>
						{:else if newTab === 'manual'}
							<div class="cosmo-input__group">
								<label for="createType" class="cosmo-label">Gerätetyp</label>
								<select
									id="createType"
									class="cosmo-select"
									name="deviceType"
									required
									bind:value={newDeviceType}
								>
									<option value={Type.PhoneOrTablet}>Smartphone oder Tablet</option>
									<option value={Type.Computer}>Computer oder Laptop</option>
									<option value={Type.Smartwatch}>Smartwatch</option>
									<option value={Type.Other}>Sonstiges</option>
								</select>
								{#if newDeviceType === Type.Computer}
									<label for="createHostname" class="cosmo-label">Name</label>
									<input
										id="createHostname"
										class="cosmo-input"
										type="text"
										name="hostname"
										required
									/>
								{/if}
								<label for="createModel" class="cosmo-label">Model</label>
								<input id="createModel" class="cosmo-input" type="text" name="model" required />
								<label for="createManufacturer" class="cosmo-label">Hersteller</label>
								<input
									id="createManufacturer"
									class="cosmo-input"
									type="text"
									name="manufacturer"
									required
								/>
								{#if [Type.Computer, Type.PhoneOrTablet].includes(newDeviceType)}
									<label for="createOperatingSystem" class="cosmo-label">Betriebssystem</label>
									<input
										id="createOperatingSystem"
										class="cosmo-input"
										type="text"
										name="os.name"
										required
									/>
									<label for="createOperatingSystemVersion" class="cosmo-label"
									>Betriebssystem Version</label
									>
									<input
										id="createOperatingSystemVersion"
										class="cosmo-input"
										type="text"
										name="os.version"
									/>
								{/if}
								{#if [Type.Computer, Type.PhoneOrTablet, Type.Smartwatch].includes(newDeviceType)}
									<label for="createStorage" class="cosmo-label">Speicherplatz in GB</label>
									<input
										id="createStorage"
										class="cosmo-input"
										type="number"
										name="storage"
										required={newDeviceType === Type.Computer}
										step="0.01"
									/>
									<label for="createRam" class="cosmo-label">Arbeitsspeicher in GB</label>
									<input
										id="createRam"
										class="cosmo-input"
										type="number"
										name="ram"
										required={newDeviceType === Type.Computer}
										step="0.01"
									/>
								{/if}
								{#if newDeviceType === Type.Computer}
									<span class="cosmo-input__header">Prozessor</span>
									<label for="createCpuManufacturer" class="cosmo-label">Hersteller</label>
									<select
										id="createCpuManufacturer"
										class="cosmo-select"
										name="cpu.manufacturer"
										required
									>
										<option value="Intel">Intel</option>
										<option value="AMD">AMD</option>
									</select>
									<label for="createCpuModel" class="cosmo-label">Model</label>
									<input
										id="createCpuModel"
										class="cosmo-input"
										type="text"
										name="cpu.model"
										required
									/>
									<label for="createCpuSpeed" class="cosmo-label">Geschwindigkeit in GHz</label>
									<input
										id="createCpuSpeed"
										class="cosmo-input"
										type="number"
										name="cpu.speed"
										required
										step="0.01"
									/>
									<label for="createCpuCores" class="cosmo-label">Kerne</label>
									<input
										id="createCpuCores"
										class="cosmo-input"
										type="number"
										name="cpu.cores"
										required
									/>
									<label for="createCpuThreads" class="cosmo-label">Threads</label>
									<input
										id="createCpuThreads"
										class="cosmo-input"
										type="number"
										name="cpu.threads"
										required
									/>
								{/if}
								{#if [Type.PhoneOrTablet, Type.Other, Type.Smartwatch].includes(newDeviceType)}
									<label for="createEol" class="cosmo-label">Supportende</label>
									<input id="createEol" class="cosmo-input" type="date" name="eol" />
								{/if}
							</div>
						{/if}
					</div>
				</div>
			</div>
			<div class="cosmo-modal__button-bar">
				<button class="cosmo-button" on:click={() => (newOpen = false)}>Verwerfen</button>
				<button class="cosmo-button" type="submit">Gerät speichern</button>
			</div>
		</form>
	</div>
{/if}
{#if editOpen}
	<div class="cosmo-modal__container">
		<form class="cosmo-modal" method="post" action="?/editDevice" use:enhance>
			<h1 class="cosmo-modal__title">Gerät bearbeiten</h1>
			<div class="cosmo-modal__content">
				<div class="cosmo-input__group">
					<input type="hidden" name="deviceId" value={selectedDevice?.id} />
					{#if selectedDeviceType === Type.Computer}
						<label for="editHostname" class="cosmo-label">Name</label>
						<input
							id="editHostname"
							class="cosmo-input"
							type="text"
							name="hostname"
							required
							value={selectedDevice?.hostname}
						/>
					{/if}
					<label for="editModel" class="cosmo-label">Model</label>
					<input
						id="editModel"
						class="cosmo-input"
						type="text"
						name="model"
						required
						value={selectedDevice?.model}
					/>
					<label for="editManufacturer" class="cosmo-label">Hersteller</label>
					<input
						id="editManufacturer"
						class="cosmo-input"
						type="text"
						name="manufacturer"
						required
						value={selectedDevice?.manufacturer}
					/>
					{#if [Type.Computer, Type.PhoneOrTablet].includes(selectedDeviceType)}
						<label for="editOperatingSystem" class="cosmo-label">Betriebssystem</label>
						<input
							id="editOperatingSystem"
							class="cosmo-input"
							type="text"
							name="os.name"
							required
							value={selectedDevice?.os?.name}
						/>
						<label for="editOperatingSystemVersion" class="cosmo-label"
						>Betriebssystem Version</label
						>
						<input
							id="editOperatingSystemVersion"
							class="cosmo-input"
							type="text"
							name="os.version"
							value={selectedDevice?.os?.version}
						/>
					{/if}
					{#if [Type.Computer, Type.PhoneOrTablet, Type.Smartwatch].includes(selectedDeviceType)}
						<label for="editStorage" class="cosmo-label">Speicherplatz in GB</label>
						<input
							id="editStorage"
							class="cosmo-input"
							type="number"
							name="storage"
							step="0.01"
							required={selectedDeviceType === Type.Computer}
							value={selectedDevice?.storage}
						/>
						<label for="editRam" class="cosmo-label">Arbeitsspeicher in GB</label>
						<input
							id="editRam"
							class="cosmo-input"
							type="number"
							name="ram"
							step="0.01"
							required={selectedDeviceType === Type.Computer}
							value={selectedDevice?.ram}
						/>
					{/if}
					{#if selectedDeviceType === Type.Computer}
						<span class="cosmo-input__header">Prozessor</span>
						<label for="editCpuManufacturer" class="cosmo-label">Hersteller</label>
						<select
							id="editCpuManufacturer"
							class="cosmo-select"
							name="cpu.manufacturer"
							required
							value={selectedDevice?.cpu?.manufacturer}
						>
							<option value="Intel">Intel</option>
							<option value="AMD">AMD</option>
						</select>
						<label for="editCpuModel" class="cosmo-label">Model</label>
						<input
							id="editCpuModel"
							class="cosmo-input"
							type="text"
							name="cpu.model"
							required
							value={selectedDevice?.cpu?.model}
						/>
						<label for="editCpuSpeed" class="cosmo-label">Geschwindigkeit in GHz</label>
						<input
							id="editCpuSpeed"
							class="cosmo-input"
							type="number"
							step="0.01"
							name="cpu.speed"
							required
							value={selectedDevice?.cpu?.speed}
						/>
						<label for="editCpuCores" class="cosmo-label">Kerne</label>
						<input
							id="editCpuCores"
							class="cosmo-input"
							type="number"
							name="cpu.cores"
							required
							value={selectedDevice?.cpu?.cores}
						/>
						<label for="editCpuThreads" class="cosmo-label">Threads</label>
						<input
							id="editCpuThreads"
							class="cosmo-input"
							type="number"
							name="cpu.threads"
							required
							value={selectedDevice?.cpu?.threads}
						/>
					{/if}
					{#if [Type.PhoneOrTablet, Type.Other, Type.Smartwatch].includes(selectedDeviceType)}
						<label for="editEol" class="cosmo-label">Supportende</label>
						<input
							id="editEol"
							class="cosmo-input"
							type="date"
							name="eol"
							value={selectedDevice?.eol?.toISOString().substring(0, 10)}
						/>
					{/if}
				</div>
			</div>
			<div class="cosmo-modal__button-bar">
				<button class="cosmo-button" on:click={() => (editOpen = false)}>Verwerfen</button>
				<button class="cosmo-button" type="submit">Gerät speichern</button>
			</div>
		</form>
	</div>
{/if}

<style lang="scss">
  .token {
    display: flex;
    justify-content: center;
  }

  .device-list {
    display: grid;
    grid-template-columns: [list] 1fr [line] 0.0625rem [details] 4fr;
    gap: 1rem;
    height: var(--page-height);

    @media screen and (width <= 1920px) {
      grid-template-columns: [list] 1fr [line] 0.0625rem [details] 2.5fr;
    }

    @media screen and (width <= 1600px) {
      grid-template-columns: [list] 1fr [line] 0.0625rem [details] 2fr;
    }
  }

  .device-list-items {
    grid-column: list;
    height: var(--page-height);
    overflow: auto;
    display: grid;
    align-items: start;
    gap: 0.5rem;
    grid-template-rows: [filter] 2rem [search] var(--control-height) [items] 1fr;
    grid-template-columns: [data] 1fr;
  }

  .device-list-items-inner {
    height: calc(var(--page-height) - 2rem - 0.5rem - var(--control-height) - 0.5rem);
    overflow: auto;
    display: grid;
    align-items: start;
    grid-auto-rows: min-content;
    grid-auto-flow: row;
    grid-row: items;
    grid-column: data;
  }

  .device-list-item {
    width: 100%;
    border-bottom: 0.0625rem solid var(--control-border-color);
    cursor: pointer;
    display: grid;
    grid-template-rows: auto auto;
    padding: 1rem;
    transition: all 0.3s;

    &:hover {
      background: var(--primary-color-alpha-25);
    }

    &.is--active {
      background: var(--primary-color);
      color: var(--white);
      border-bottom-color: var(--primary-color);
      border-radius: var(--border-radius);

      &:hover {
        background: var(--primary-color);
      }
    }

    &:last-of-type {
      border-bottom: none;
    }
  }

  .device-list-separator {
    grid-column: line;
    height: var(--page-height);
    width: 0.0625rem;
    background: var(--control-border-color);
  }

  .device-list-details {
    grid-column: details;
    height: var(--page-height);
    overflow: auto;
    width: 100%;
    display: grid;
    grid-template-rows: [title] 2.75rem [toolbar] var(--control-height) [inner] 1fr;
    grid-auto-rows: auto;
    gap: 0.5rem;
  }

  .device-list-details-inner {
    height: calc(var(--page-height) - 0.5rem - 2.75rem - 0.5rem - var(--control-height));
    overflow: auto;
  }

  .device-title {
    font-size: var(--h4-font-size);
    font-family: var(--font-family-heading);
    font-weight: var(--font-weight-light);
    width: 100%;
    text-overflow: ellipsis;
    overflow: hidden;
    word-break: keep-all;
    white-space: nowrap;
  }

  .device-subtitle {
    font-size: var(--h6-font-size);
  }

  .device-filter-bar {
    display: flex;
    gap: 1rem;
    margin-bottom: 0.5rem;
    position: sticky;
    flex-flow: row nowrap;
    grid-row: filter;
    grid-column: data;
    width: 100%;
    overflow: auto;
  }

  .device-search-bar {
    margin-bottom: 0.5rem;
    font-size: 1.25rem;
    grid-row: search;
    grid-column: data;
  }

  .device-filter-bubble {
    background: var(--primary-color);
    border-radius: 50%;
    height: 0.5rem;
    width: 0.5rem;
    transition: all 0.3s;

    .active & {
      background: var(--white);
    }
  }

  .device-filter-type {
    color: var(--black);
    background: transparent;
    border-radius: var(--border-radius);
    position: relative;
    padding: 0.25rem 0.5rem;
    align-items: center;
    display: flex;
    gap: 0.5rem;
    cursor: pointer;
    border: 0.0625rem solid var(--primary-color);
    line-height: 1.25rem;

    &.active {
      color: var(--white);
      background: var(--primary-color);
    }
  }

  .add-button {
    grid-row: items;
    grid-column: data;
    place-self: end right;
  }

  .jewels-new {
    display: grid;
    grid-template-columns: 1fr 1fr;
  }
</style>
